######################################################################
# Automatically generated by qmake (3.1) Wed Jun 22 18:23:51 2022
######################################################################

TEMPLATE = app
TARGET = math
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/brick.hpp \
           src/engine_manager.hpp \
           src/mainwindow.hpp \
           src/rope.hpp \
           src/scene.hpp \
           cmake-build-debug/CMakeFiles/ShowIncludes/foo.h \
           cmake-build-release/CMakeFiles/ShowIncludes/foo.h \
           cmake-build-debug/brick7rope-modeling_autogen/UVLADIE3JM/moc_engine_manager.cpp \
           cmake-build-debug/brick7rope-modeling_autogen/UVLADIE3JM/moc_mainwindow.cpp \
           cmake-build-debug/untitled7_autogen/UVLADIE3JM/moc_engine_manager.cpp \
           cmake-build-debug/untitled7_autogen/UVLADIE3JM/moc_mainwindow.cpp \
           cmake-build-debug/untitled_autogen/UVLADIE3JM/moc_engine_manager.cpp \
           cmake-build-debug/untitled_autogen/UVLADIE3JM/moc_mainwindow.cpp \
           cmake-build-release/untitled_autogen/UVLADIE3JM/moc_engine_manager.cpp \
           cmake-build-release/untitled_autogen/UVLADIE3JM/moc_mainwindow.cpp
SOURCES += src/engine_manager.cpp \
           src/main.cpp \
           src/mainwindow.cpp \
           src/scene.cpp \
           cmake-build-debug/brick7rope-modeling_autogen/mocs_compilation.cpp \
           cmake-build-debug/untitled7_autogen/mocs_compilation.cpp \
           cmake-build-debug/untitled_autogen/mocs_compilation.cpp \
           cmake-build-release/untitled_autogen/mocs_compilation.cpp \
           cmake-build-debug/CMakeFiles/ShowIncludes/main.c \
           cmake-build-release/CMakeFiles/ShowIncludes/main.c \
           cmake-build-debug/CMakeFiles/3.22.3/CompilerIdC/CMakeCCompilerId.c \
           cmake-build-debug/CMakeFiles/3.22.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           cmake-build-release/CMakeFiles/3.22.3/CompilerIdC/CMakeCCompilerId.c \
           cmake-build-release/CMakeFiles/3.22.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
